# ---- constants ----

# ---- prompt ----
format = """
$os\
$jobs\
$username\
$hostname\
$directory\
$git_branch\
$nodejs\
$scala\
$python\
$cmd_duration\
$fill\
\n\
$character
"""

add_newline = true

#---- theme ----

palette = "ayu"

[palettes.ayu]
background = '#212733'
foreground = '#d9d7ce'
cursor = '#ffcc66'
selection_background = '#343f4c'
color0 = '#191e2a'
color8 = '#686868'
color1 = '#ed8274'
color9 = '#f28779'
color2  = '#a6cc70'
color10 = '#bae67e'
color3  = '#fad07b'
color11 = '#ffd580'
color4  = '#6dcbfa'
color12 = '#73d0ff'
color5  = '#cfbafa'
color13 = '#d4bfff'
color6  = '#90e1c6'
color14 = '#95e6cb'
color7  = '#c7c7c7'
color15 = '#ffffff'
selection_foreground = '#212733'

# ---- Tools ----

[fill]
symbol = ' '

[os]
format = "[$symbol]($style)"
style = "fg:color12 bg:background"
disabled = false

[os.symbols]
Windows = "  "
Arch = "  "
NixOS = "  "
Fedora = "  "

[jobs]
format = '[$number$symbol ]($style)'
symbol = '✦'
style = 'fg:foreground bg:background'

[username]
show_always = true
format = '[$user@]($style)'
style_user = 'fg:foreground bg:background'
style_root = 'fg:foreground bg:background'

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname ]($style)'
style = 'fg:foreground bg:background'

[directory]
format = '[  $path ]($style)[$read_only]($read_only_style)'
style = 'fg:background bg:color12'

[git_branch]
format = '[ on $symbol$branch(:$remote_branch) ]($style)'
style = 'fg:background bg:color11'

[cmd_duration]
show_milliseconds = true
format = "[ 󰅒 $duration ]($style) "
style = "italic fg:background bg:color14"

[character]
format = '$symbol '
success_symbol = '[❯](foreground)'
error_symbol = '[❯](foreground)'

# ---- Languages ----

[nodejs]
format = "[ $symbol$version ]($style)"
style = "fg:background bg:color10"
disabled = false
symbol = "󰎙 "

[scala]
format = "[ $symbol$version ]($style)"
style = "fg:background bg:color9"
disabled = true
detect_files = ["pom.xml"]
symbol = " "

[python]
format = "[ $symbol$version ]($style)"
style = "fg:background bg:color7"
disabled = false
symbol = ' '