# ---- constants ----

# ---- prompt ----
format = """
$os\
$jobs\
$username\
$hostname\
$directory\
$git_branch\
$cmd_duration\
$fill\
\n\
$character\
"""

add_newline = true

#---- theme ----

palette = "ayu"

[palettes.ayu]
background = '#212733'
foreground = '#d9d7ce'
cursor = '#ffcc66'
selection_background = '#343f4c'
color0 = '#191e2a'
color8 = '#686868'
color1 = '#ed8274'
color9 = '#f28779'
color2 = '#a6cc70'
color10 = '#bae67e'
color3 = '#fad07b'
color11 = '#ffd580'
color4 = '#6dcbfa'
color12 = '#73d0ff'
color5 = '#cfbafa'
color13 = '#d4bfff'
color6 = '#90e1c6'
color14 = '#95e6cb'
color7 = '#c7c7c7'
color15 = '#ffffff'
selection_foreground = '#212733'

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

# ---- Tools ----

[fill]
symbol = ' '

[os]
format = "[$symbol]($style)"
style = "fg:color12 bg:background"
disabled = false

[os.symbols]
Windows = "  "
Arch = "  "
NixOS = "  "
Fedora = "  "

[jobs]
format = '[$number$symbol ]($style)'
symbol = '✦'
style = 'fg:foreground bg:background'

[username]
show_always = true
format = '[$user@]($style)'
style_user = 'fg:foreground bg:background'
style_root = 'fg:foreground bg:background'

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname ]($style)'
style = 'fg:foreground bg:background'

[directory]
format = '[  $path ]($style)[$read_only]($read_only_style)'
style = 'fg:background bg:color12'

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
style = 'fg:background bg:color5'

[cmd_duration]
show_milliseconds = true
format = "[ 󰅒 $duration ]($style) "
style = "italic fg:color14"

[package]
disabled = true

[character]
format = "$symbol "
success_symbol = '[❯](color10)'
error_symbol = '[❯](color9)'

# ---- Languages ----

# [nodejs]
# format = "[ $symbol$version ]($style)"
# style = "fg:background bg:color10"
# disabled = false
# symbol = "󰎙 "

# [scala]
# format = "[ $symbol$version ]($style)"
# style = "fg:background bg:color9"
# disabled = true
# detect_files = ["pom.xml"]
# symbol = " "

# [python]
# format = "[ $symbol$version ]($style)"
# style = "fg:background bg:color7"
# disabled = false
# symbol = ' '
